name: CFML Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CommandBox
      uses: ortus-solutions/commandbox-action@v2.0.0

    - name: Install dependencies
      run: box install

    - name: Run tests
      run: box testbox run
